base_url="https://localhost:8000"
client_id="t94c30lVobGpaZM244aI4OLcbME51Ivu"
client_secret="_szX6ezAse9dT2GXvDNTQCKIurgVc-8p4z8D7pFMPQNahAyc3cAVXcU34gON4JWO"
username="robinjefferson123@gmail.com"
password="ChangeMePLZ!!"
